name: GitHub README stats generator
description: Dynamically generated stats for your GitHub README
inputs:
  card:
    description: 'Type of card: one of stats (default), repo, langs, wakatime, gist.'
    required: false
    default: stats
  options:
    description: Options for the card
    required: false
    default: username=${{ github.repository_owner }}
  path:
    description: Output path for SVG file (relative path; include filename with .svg)
    required: false
    default: grs/out.svg
  token:
    description: GitHub token; normally no need to set it
    required: false
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
branding:
  color: green
  icon: bar-chart

runs:
  using: composite
  steps:
    - name: Get package-lock.json path
      id: lock
      run: |
        cd $GITHUB_ACTION_PATH
        lock=$(pwd)/package-lock.json
        modules=$(pwd)/node_modules
        if command -v cygpath &> /dev/null; then
          lock=$(cygpath -w $lock)
          modules=$(cygpath -w $modules)
        fi
        echo "lock=$lock" >> $GITHUB_OUTPUT
        echo "modules=$modules" >> $GITHUB_OUTPUT
        cd $GITHUB_WORKSPACE
      shell: bash
      # This step is needed because ${{ github.action_path }} has relative pathing (it ends with /./).

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Restore cache
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ steps.lock.outputs.modules }}
        key: ${{ runner.os }}-grs-modules-${{ hashFiles(steps.lock.outputs.lock) }}

    - name: CI
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: |
        cd $GITHUB_ACTION_PATH
        npm ci
        cd $GITHUB_WORKSPACE
      shell: bash

    - name: Save cache
      if: steps.cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.lock.outputs.modules }}
        key: ${{ runner.os }}-grs-modules-${{ hashFiles(steps.lock.outputs.lock) }}

    - name: Run
      run: node $GITHUB_ACTION_PATH/index.js
      env:
        GRS_CARD: ${{ inputs.card }}
        GRS_OPTIONS: ${{ inputs.options }}
        GRS_PATH: ${{ inputs.path }}
        PAT_1: ${{ inputs.token }}
      shell: bash
