on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  generate:
    name: Generate
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Stats
        uses: ./
        with:
          card: stats
          options: username=${{ github.repository_owner }}
          path: grs/stats-${{ matrix.platform }}.svg

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stats-${{ matrix.platform }}
          path: grs

  push:
    name: Push
    permissions: write-all
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Download (Ubuntu)
        uses: actions/download-artifact@v4
        with:
          name: stats-ubuntu-latest
          path: grs

      - name: Download (Windows)
        uses: actions/download-artifact@v4
        with:
          name: stats-windows-latest
          path: grs

      - name: Download (macOS)
        uses: actions/download-artifact@v4
        with:
          name: stats-macos-latest
          path: grs

      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-action-output
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
